from app.models.role import Role
from app.models.user import User
from app.models.camera import Camera
from app.models.incident import Incident
from app.models.detection import Detection
from app.models.alert import Alert
from app.models.ai_summary import AISummary
from app.models.report import Report
from app.models.chat import ChatHistory
from app.models.login_history import LoginHistory
from app.models.token_blacklist import TokenBlacklist
from app.models.audit_log import AuditLog
from app.models.setting import Setting
from app.models.system_log import SystemLog
from .ai_summary import AISummary