"""
incident_manager.py

Keeps track of active incidents generated by the AI engine.

Instead of creating a new incident for every frame,
we remember which tracked object already has an incident.

track_id  ---> incident information
"""

import time

# ==========================================================
# Active Incidents
# ==========================================================

# Structure:
#
# active_incidents = {
#
#     5: {
#         "incident_id": 21,
#         "event": "Person Detected",
#         "risk": "LOW",
#         "last_seen": 1721991122.55
#     },
#
#     12: {
#         "incident_id": 22,
#         "event": "Restricted Area Intrusion",
#         "risk": "HIGH",
#         "last_seen": 1721991124.02
#     }
# }
#

active_incidents = {}


# ==========================================================
# Check if Incident Exists
# ==========================================================

def has_active_incident(track_id: int) -> bool:
    """
    Returns True if the object already has an active incident.
    """

    return track_id in active_incidents


# ==========================================================
# Get Incident Information
# ==========================================================

def get_incident(track_id: int):
    """
    Returns stored incident dictionary.

    Returns None if not found.
    """

    return active_incidents.get(track_id)


# ==========================================================
# Register New Incident
# ==========================================================

def register_incident(
    track_id: int,
    incident_id: int,
    event: str,
    risk: str,
):
    """
    Register a newly created incident.
    """

    active_incidents[track_id] = {

        "incident_id": incident_id,

        "event": event,

        "risk": risk,

        "last_seen": time.time(),

    }


# ==========================================================
# Update Last Seen Time
# ==========================================================

def update_last_seen(track_id: int):
    """
    Refresh timestamp whenever the object
    appears again.
    """

    if track_id in active_incidents:

        active_incidents[track_id]["last_seen"] = time.time()


# ==========================================================
# Remove Incident
# ==========================================================

def remove_incident(track_id: int):
    """
    Remove object from active incident list.
    """

    if track_id in active_incidents:

        del active_incidents[track_id]


# ==========================================================
# Cleanup Old Incidents
# ==========================================================

def cleanup_expired_incidents(timeout_seconds: int = 30):
    """
    Remove incidents that haven't been seen
    for 'timeout_seconds'.

    Returns:
        list of removed track IDs.
    """

    current_time = time.time()

    expired_tracks = []

    for track_id, info in list(active_incidents.items()):

        elapsed = current_time - info["last_seen"]

        if elapsed > timeout_seconds:

            expired_tracks.append(track_id)

            del active_incidents[track_id]

    return expired_tracks


# ==========================================================
# Get All Active Incidents
# ==========================================================

def get_all_active_incidents():
    """
    Returns all active incidents.
    """

    return active_incidents


# ==========================================================
# Count Active Incidents
# ==========================================================

def total_active_incidents():
    """
    Returns number of active incidents.
    """

    return len(active_incidents)


# ==========================================================
# Reset Manager
# ==========================================================

def clear_all():
    """
    Clears all active incidents.

    Useful while testing.
    """

    active_incidents.clear()


# ==========================================================
# Debug
# ==========================================================

def print_active_incidents():
    """
    Pretty print active incidents.
    """

    print("\n========== ACTIVE INCIDENTS ==========")

    if not active_incidents:
        print("No Active Incidents")
        return

    for track_id, info in active_incidents.items():

        print(f"Track ID     : {track_id}")
        print(f"Incident ID  : {info['incident_id']}")
        print(f"Event        : {info['event']}")
        print(f"Risk         : {info['risk']}")
        print(f"Last Seen    : {round(info['last_seen'],2)}")
        print("--------------------------------------")